---
# This is used to control the deploy tasks in the rake file.
# Set an environment variable ENV to one of the values below. The rake task
# will then use the key/values for that environment to set the cloud foundry
# target.
# eg: to target Bluemix dev space for your organisation execute the following:
# $ export ENV=public-dev
# $ rake deploy

env:
  au-syd-dev:
    api: api.au-syd.bluemix.net
    space: dev
    organisation: iwinoto@au1.ibm.com
  au-syd-demo:
    api: api.au-syd.bluemix.net
    space: demo
    organisation: iwinoto@au1.ibm.com
  au-syd-test:
    api: api.au-syd.bluemix.net
    space: test
    organisation: iwinoto@au1.ibm.com
  au-syd-prod:
    api: api.au-syd.bluemix.net
    space: prod
    organisation: iwinoto@au1.ibm.com